# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "feature/member" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: myprojectbucket00
  CODE_DEPLOY_APPLICATION_NAME: gitaction-app
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: gitaction-release-group
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
  
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell 
      - name: Clean temp directory
        run: |
          rm -rf *
          cp -r $GITHUB_WORKSPACE . 

      - name: archive drcloud 
        run: tar cvfz ./drcloud.tar.gz *

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: $AWS_REGION
          
      - name: upload to S3
        run: aws s3 cp --region $AWS_REGION ./drcloud.tar.gz s3://$S3_BUCKET_NAME/archive/
        
      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name $CODE_DEPLOY_APPLICATION_NAME
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name $gitaction-release-group
          --s3-location bucket$S3_BUCKET_NAME,bundleType=tgz,key=archive/drcloud.tar.gz
